package:
  name: treetool
  version: "1.0"

source:
  #git_url: https://github.com/porteratzo/TreeTool/tree/setup
  path: ..

requirements:
  build:
    - python
    - setuptools

  run:
    - python>=3.8,<3.9
    - numpy>=1.17
    - qhull
    - pclpy

about:
  license: MIT
  license_family: MIT
  summary: Tool to extract tree trunks and diameter at breast height from TLS forest point clouds