package:
  name: treetool
  version: "1.0.0"

source:
  git_url: https://github.com/porteratzo/treetool

requirements:
  build:
    - python >=3.8,<3.9
    - setuptools
    - pip

  run:
    - python >=3.8,<3.9
    - numpy
    - pandas
    - matplotlib
    - qhull
    - pclpy
    - pip

about:
  license: MIT
  license_family: MIT
  summary: Tool to extract tree trunks and diameter at breast height from TLS forest point clouds